name: Makefile CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.7.0

    - name: Install pipenv
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Quality
      run: make quality_checks

    - name: Test
      run: make test

  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make build

    - name: Login
      run: make login
      env:
        AZ_REGISTRY_USERNAME: ${{ secrets.AZ_REGISTRY_USERNAME }}
        AZ_REGISTRY_PASSWORD: ${{ secrets.AZ_REGISTRY_PASSWORD }}

    - name: Push
      run: make push

    - name: Deploy
      run: make deploy
      env:
        PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
