name: Makefile CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code_style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.7.0

    - name: Install pipenv
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Quality
      run: make quality_checks
